msg:
  headers:
    type: 20
    length: 64
  types:
    disconnect: "!DISCONNECT"
    file: "!FILE"
    filename: "!FILENAME"
    name: "!NAME"
    register: "!REGISTER"
    response: "!RESPONSE"
port: 5050
format: "utf-8"
