msg:
  headers:
    type: 20
    length: 64
  types: 
    disconnect: "!DISCONNECT"
    name: "!NAME"
    file: "!FILE"
    filename: "!FILENAME"
    response: "!RESPONSE"
port: 5050
format: "utf-8"
disconnect_message: "!DISCONNECT"